name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  # add manual trigger button
  workflow_dispatch:

jobs:
  build:
    name: Build (Go ${{ matrix.go-version }})
    strategy:
      matrix:
        go-version: [stable, oldstable]

    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Fetch dependencies
        run: go mod download -x

      - name: Run tests
        run: go test -v ./...

      - name: Install xcaddy
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

      - name: Build caddy plugin
        run: xcaddy build
